const afghanistanProvinces = {
  Badakhshan: [
    "Fayzabad",
    "Baharak",
    "Yaftali Sufla",
    "Yamgan",
    "Yawan",
    "Zebak",
    "Arghanj Khwa",
    "Argo",
    "Darayim",
    "Darvaz",
  ],
  Badghis: [
    "Qala-e-Naw",
    "Ab Kamari",
    "Ghormach",
    "Jawand",
    "Muqur",
    "Murghab",
    "Qadis",
  ],
  Baghlan: [
    "Puli Khumri",
    "Baghlani Jadid",
    "Burka",
    "Dahana-i-Ghuri",
    "Dushi",
    "Guzargahi Nur",
    "Khinjan",
  ],
  Balkh: [
    "Mazar-i-Sharif",
    "Balkh",
    "Charbolak",
    "Chimtal",
    "Dawlatabad",
    "Dihdadi",
    "Kaldar",
  ],
  Bamyan: ["Bamyan", "Kahmard", "Panjab", "Shibar", "Waras", "Yakawlang"],
  Daykundi: ["Nili", "Ashtarlay", "Kiti", "Khedir", "Miramor", "Sangi Takht"],
  Farah: [
    "Farah",
    "Anar Dara",
    "Bakwa",
    "Bala Buluk",
    "Gulistan",
    "Khaki Safed",
    "Lash Wa Juwayn",
  ],
  Faryab: [
    "Maymana",
    "Almar",
    "Andkhoy",
    "Bilchiragh",
    "Dawlat Abad",
    "Gurziwan",
    "Khani Chahar Bagh",
  ],
  Ghazni: [
    "Ghazni",
    "Ab Band",
    "Ajristan",
    "Andar",
    "Dih Yak",
    "Gelan",
    "Giro",
  ],
  Ghor: [
    "Chaghcharan",
    "Dawlat Yar",
    "Du Layna",
    "Lal Wa Sarjangal",
    "Pasaband",
    "Saghar",
    "Shahrak",
  ],
  Helmand: [
    "Lashkargah",
    "Baghran",
    "Dishu",
    "Garmsir",
    "Kajaki",
    "Musa Qala",
    "Nad Ali",
  ],
  Herat: [
    "Herat",
    "Adraskan",
    "Chishti Sharif",
    "Karoukh",
    "Gulran",
    "Guzara",
    "Injil",
  ],
  Jowzjan: [
    "Sheberghan",
    "Aqcha",
    "Darzab",
    "Fayzabad",
    "Khamyab",
    "Khaniqa",
    "Mardyan",
  ],
  Kabul: [
    "Kabul",
    "Bagrami",
    "Chahar Asyab",
    "Deh Sabz",
    "Farza",
    "Guldara",
    "Istalif",
  ],
  Kandahar: [
    "Kandahar",
    "Arghandab",
    "Arghistan",
    "Daman",
    "Ghorak",
    "Khakrez",
    "Maruf",
  ],
  Kapisa: [
    "Mahmud Raqi",
    "Alasay",
    "Hesa Awal Kohistan",
    "Hesa Duwum Kohistan",
    "Koh Band",
    "Nijrab",
    "Tagab",
  ],
  Khost: [
    "Khost",
    "Bak",
    "Gurbuz",
    "Jaji Maydan",
    "Mandozayi",
    "Musa Khel",
    "Nadir Shah Kot",
  ],
  Kunar: [
    "Asadabad",
    "Asmar",
    "Bar Kunar",
    "Chapa Dara",
    "Chawkay",
    "Dangam",
    "Dara-I-Pech",
  ],
  Kunduz: [
    "Kunduz",
    "Ali Abad",
    "Archi",
    "Chahar Dara",
    "Imam Sahib",
    "Khan Abad",
    "Qalay-I-Zal",
  ],
  Laghman: ["Mihtarlam", "Alingar", "Alishing", "Dawlat Shah", "Qarghayi"],
  Logar: [
    "Puli Alam",
    "Azra",
    "Baraki Barak",
    "Charkh",
    "Kharwar",
    "Khoshi",
    "Mohammad Agha",
  ],
  Nangarhar: [
    "Jalalabad",
    "Achin",
    "Bati Kot",
    "Behsud",
    "Chaparhar",
    "Dara-I-Nur",
    "Dih Bala",
  ],
  Nimruz: [
    "Zaranj",
    "Chahar Burjak",
    "Chakhansur",
    "Kang",
    "Khash Rod",
    "Delaram",
  ],
  Nuristan: [
    "Parun",
    "Bargi Matal",
    "Du Ab",
    "Kamdesh",
    "Mandol",
    "Nurgram",
    "Wama",
  ],
  Paktia: [
    "Gardez",
    "Ahmad Aba",
    "Dand Wa Patan",
    "Jaji",
    "Jani Khil",
    "Lazha Ahmad Khel",
    "Sayid Karam",
  ],
  Paktika: ["Sharana", "Barmal", "Dila", "Gayan", "Gomal", "Mata Khan", "Nika"],
  Panjshir: ["Bazarak", "Anaba", "Darah", "Khenj", "Paryan", "Rokha", "Shotul"],
  Parwan: [
    "Charikar",
    "Bagram",
    "Chaharikar",
    "Ghorband",
    "Jabalussaraj",
    "Kohi Safi",
    "Salang",
  ],
  Samangan: [
    "Aybak",
    "Dara-I-Sufi Balla",
    "Dara-I-Sufi Payin",
    "Feroz Nakhchir",
    "Hazrati Sultan",
    "Khuram Wa Sarbagh",
  ],
  "Sar-e Pol": [
    "Sar-e Pol",
    "Balkhab",
    "Gosfandi",
    "Kohistanat",
    "Sangcharak",
    "Sayyad",
    "Sozma Qala",
  ],
  Takhar: [
    "Taloqan",
    "Baharak",
    "Banghi",
    "Chah Ab",
    "Chal",
    "Darqad",
    "Dashti Qala",
  ],
  Urozgan: [
    "Tarinkot",
    "Chora",
    "Deh Rawud",
    "Gizab",
    "Khas Urozgan",
    "Shahidi Hassas",
  ],
  Wardak: [
    "Maidan Shahr",
    "Chaki Wardak",
    "Daimirdad",
    "Hisa-I-Awali Bihsud",
    "Jalrez",
    "Markazi Bihsud",
  ],
  Zabul: [
    "Qalat",
    "Argahandab",
    "Atghar",
    "Dey Chopan",
    "Kakar",
    "Mizan",
    "Shah Joy",
  ],
};

export default afghanistanProvinces;
