export const AFGHANISTAN_PROVINCES = {
  Badakhshan: [
    "Fayzabad",
    "Baharak",
    "Darayim",
    "Khwahan",
    "Kishim",
    "Jurum",
    "Ragh",
    "Shighnan",
    "Shuhada",
    "Warduj",
    "Yaftali Sufla",
    "Yamgan",
    "Yawan",
    "Zebak",
  ],
  Badghis: [
    "Qala-e-Naw",
    "Ab Kamari",
    "Ghormach",
    "Jawand",
    "Muqur",
    "Murghab",
    "Qadis",
    "Qala-e-Naw",
  ],
  Baghlan: [
    "Puli Khumri",
    "Andarab",
    "Baghlan-e-Jadid",
    "Burka",
    "Dahana-e-Ghuri",
    "Dushi",
    "Farang Wa Gharu",
    "Guzargahi Nur",
    "Khinjan",
    "Khost Wa Fereng",
    "Khwaja Hijran",
    "Nahrin",
    "Puli Hisar",
  ],
  Balkh: [
    "Mazar-e-Sharif",
    "Balkh",
    "Charbolak",
    "Chimtal",
    "Dawlatabad",
    "Dihdadi",
    "Kaldar",
    "Khulm",
    "Kishindih",
    "Marmul",
    "Nahri Shahi",
    "Sholgara",
    "Shortepa",
    "Zari",
  ],
  Bamyan: [
    "Bamyan",
    "Kahmard",
    "Panjab",
    "Sayghan",
    "Shibar",
    "Waras",
    "Yakawlang",
  ],
  Daykundi: [
    "Nili",
    "Ashtarlay",
    "Ishtarlay",
    "Kiti",
    "Khadir",
    "Khedir",
    "Miramor",
    "Nili",
    "Sangi Takht",
    "Shahristan",
  ],
  Farah: [
    "Farah",
    "Anar Dara",
    "Bakwa",
    "Bala Buluk",
    "Farah Rod",
    "Gulistan",
    "Khaki Safed",
    "Lash Wa Juwayn",
    "Pur Chaman",
    "Pusht Rod",
    "Qala-e-Kah",
    "Shib Koh",
  ],
  Faryab: [
    "Maymana",
    "Almar",
    "Andkhoy",
    "Bilchiragh",
    "Dawlat Abad",
    "Gurziwan",
    "Khani Chahar Bagh",
    "Khwaja Sabz Posh",
    "Kohistan",
    "Qaysar",
    "Qurghan",
    "Pashtun Kot",
    "Shirin Tagab",
  ],
  Ghazni: [
    "Ghazni",
    "Ab Band",
    "Ajristan",
    "Andar",
    "Dih Yak",
    "Gelan",
    "Giro",
    "Jaghori",
    "Khugiani",
    "Malistan",
    "Muqur",
    "Nawa",
    "Nawur",
    "Qarabagh",
    "Rashidan",
    "Waghaz",
    "Zana Khan",
  ],
  Ghor: [
    "Chaghcharan",
    "Charsada",
    "Dawlat Yar",
    "Du Layna",
    "Lal Wa Sarjangal",
    "Pasaband",
    "Saghar",
    "Shahrak",
    "Taywara",
    "Tulak",
  ],
  Helmand: [
    "Lashkargah",
    "Baghran",
    "Dishu",
    "Garmsir",
    "Kajaki",
    "Khanashin",
    "Musa Qala",
    "Nad Ali",
    "Nahr-e-Saraj",
    "Nawa-e-Barakzayi",
    "Nawzad",
    "Sangin",
    "Washir",
  ],
  Herat: [
    "Herat",
    "Adraskan",
    "Chishti Sharif",
    "Farsi",
    "Ghoryan",
    "Gulran",
    "Guzara",
    "Injil",
    "Karukh",
    "Kohsan",
    "Kushk",
    "Kushki Kuhna",
    "Obe",
    "Pashtun Zarghun",
    "Shindand",
    "Zinda Jan",
  ],
  Jowzjan: [
    "Sheberghan",
    "Aqcha",
    "Darzab",
    "Fayzabad",
    "Khamyab",
    "Khaniqa",
    "Khwaja Du Koh",
    "Mardyan",
    "Mingajik",
    "Qarqin",
    "Qush Tepa",
    "Shibirghan",
  ],
  Kabul: [
    "Kabul",
    "Bagrami",
    "Chahar Asyab",
    "Deh Sabz",
    "Farza",
    "Guldara",
    "Istalif",
    "Kabul",
    "Kalakan",
    "Khaki Jabbar",
    "Mir Bacha Kot",
    "Musayi",
    "Paghman",
    "Qarabagh",
    "Shakardara",
    "Surobi",
  ],
  Kandahar: [
    "Kandahar",
    "Arghandab",
    "Arghistan",
    "Daman",
    "Ghorak",
    "Khakrez",
    "Maruf",
    "Maywand",
    "Miyan Nasheen",
    "Naish",
    "Panjwayi",
    "Reg",
    "Shah Wali Kot",
    "Shorabak",
    "Spin Boldak",
    "Zhari",
  ],
  Kapisa: [
    "Mahmud-i-Raqi",
    "Alasay",
    "Hesa Awal Kohistan",
    "Hesa Duwum Kohistan",
    "Koh Band",
    "Mahmud Raqi",
    "Nijrab",
    "Tagab",
  ],
  Khost: [
    "Khost",
    "Bak",
    "Gurbuz",
    "Jaji Maydan",
    "Mandozayi",
    "Musa Khel",
    "Nadir Shah Kot",
    "Qalandar",
    "Sabari",
    "Shamal",
    "Spera",
    "Tani",
    "Tere Zayi",
  ],
  Kunar: [
    "Asadabad",
    "Asmar",
    "Bar Kunar",
    "Chapa Dara",
    "Chawkay",
    "Dangam",
    "Dara-I-Pech",
    "Ghaziabad",
    "Khas Kunar",
    "Marawara",
    "Narang Wa Badil",
    "Nari",
    "Nurgal",
    "Sawkai",
    "Shaygal Wa Shiltan",
    "Wata Pur",
  ],
  Kunduz: [
    "Kunduz",
    "Aliabad",
    "Archi",
    "Chahar Dara",
    "Imam Sahib",
    "Khanabad",
    "Qalay-I-Zal",
  ],
  Laghman: ["Mehtar Lam", "Alingar", "Alishing", "Dawlat Shah", "Qarghayi"],
  Logar: [
    "Pul-e-Alam",
    "Azra",
    "Baraki Barak",
    "Charkh",
    "Kharwar",
    "Khoshi",
    "Mohammad Agha",
    "Pul-e-Alam",
  ],
  Nangarhar: [
    "Jalalabad",
    "Achin",
    "Bati Kot",
    "Bihsud",
    "Chaparhar",
    "Dara-I-Nur",
    "Dih Bala",
    "Dur Baba",
    "Goshta",
    "Hesarak",
    "Kama",
    "Khogyani",
    "Kot",
    "Kuz Kunar",
    "Lal Pur",
    "Momand Dara",
    "Nazyan",
    "Pachir Wa Agam",
    "Rodat",
    "Sherzad",
    "Shinwar",
    "Surkh Rod",
  ],
  Nimruz: [
    "Zaranj",
    "Chahar Burjak",
    "Chakhansur",
    "Kang",
    "Khash Rod",
    "Delaram",
  ],
  Nuristan: [
    "Parun",
    "Bargi Matal",
    "Du Ab",
    "Kamdesh",
    "Mandol",
    "Nurgram",
    "Wama",
    "Waygal",
  ],
  Paktia: [
    "Gardez",
    "Ahmad Aba",
    "Dand Wa Patan",
    "Jadran",
    "Janikhel",
    "Lazha Mangal",
    "Sayed Karam",
    "Shamal",
    "Shwak",
    "Tsamkani",
    "Zadran",
    "Zazi",
    "Zurmat",
  ],
  Paktika: [
    "Sharana",
    "Barmal",
    "Dila",
    "Gayan",
    "Gomal",
    "Janikhel",
    "Mata Khan",
    "Nika",
    "Omna",
    "Sar Hawza",
    "Sarobi",
    "Sharan",
    "Terwa",
    "Urgun",
    "Waza Khwa",
    "Wor Mamay",
    "Yahya Khel",
    "Yosuf Khel",
    "Zarghun Shahr",
    "Ziruk",
  ],
  Panjshir: ["Bazarak", "Anaba", "Darah", "Khenj", "Paryan", "Rokha", "Shotul"],
  Parwan: [
    "Charikar",
    "Bagram",
    "Chaharikar",
    "Ghorband",
    "Jabalussaraj",
    "Kohi Safi",
    "Salang",
    "Sayed Khel",
    "Shekh Ali",
    "Shinwari",
    "Surkhi Parsa",
  ],
  Samangan: [
    "Aybak",
    "Darah Sof-e Payan",
    "Darah Sof-e Bala",
    "Feroz Nakhchir",
    "Hazrat Sultan",
    "Khuram Wa Sarbagh",
    "Ruyi Du Ab",
  ],
  "Sar-e Pol": [
    "Sar-e Pol",
    "Balkhab",
    "Gosfandi",
    "Kohistanat",
    "Sangcharak",
    "Sayed",
    "Sozma Qala",
  ],
  Takhar: [
    "Taloqan",
    "Baharak",
    "Bangi",
    "Chah Ab",
    "Chal",
    "Darqad",
    "Dashti Qala",
    "Farkhar",
    "Hazar Sumuch",
    "Ishkamish",
    "Kalafgan",
    "Khwaja Bahauddin",
    "Rustaq",
    "Warsaj",
    "Yangi Qala",
  ],
  Urozgan: [
    "Tarinkot",
    "Chora",
    "Deh Rawud",
    "Gizab",
    "Khas Urozgan",
    "Shahidi Hassas",
    "Tarinkot",
  ],
  Wardak: [
    "Maidan Shar",
    "Chaki Wardak",
    "Day Mirdad",
    "Hisa-I-Awali Bihsud",
    "Jaghatu",
    "Jalrez",
    "Markazi Bihsud",
    "Maidan Shar",
    "Nirkh",
    "Saydabad",
  ],
  Zabul: [
    "Qalat",
    "Argahandab",
    "Atghar",
    "Dey Chopan",
    "Kakar",
    "Mizan",
    "Naw Bahar",
    "Qalat",
    "Shahjoy",
    "Shamulzayi",
    "Shinkay",
    "Tarnak Wa Jaldak",
  ],
};
